import = [ "~/.config/alacritty/themes/themes/hyper.toml" ]
shell = "/usr/bin/zsh"

[scrolling]
history = 10000
multiplier = 5

[terminal]
osc52 = "CopyPaste"



[window]

#opacity = 0.9

padding = { x = 13, y = 10}

dynamic_padding = true

[font]

normal = { family = "monospace", style = "Regular" } 

bold = { family = "monospace", style = "Bold" }

italic = { family = "monospace", style = "Italic" }

bold_italic = { family = "monospace", style = "Bold Italic" }

size = 8

[cursor]

style = { shape = "Block", blinking = "On"}
blink_interval = 500
blink_timeout = 1
unfocused_hollow = true
thickness = 0.2
# style.blinking = "On"
